### ISSUE TITLE
Is the repository dead?

### ISSUE THREAD

**Issue by khanguy00** [BluezoneGlobal/bluezone-app#13]
I haven't seen the maintainer actually reply any issue in this repo and its sister's repositories for a while.

The source code is also outdated with the app on Play Store [here](https://play.google.com/store/apps/details?id=com.mic.bluezone).

Looks like this repo is just a shadow, and the real one is a closed source project.

@ any maintainers: If you're still alive, and this project are continuing, please response and let the your Github community know. Thanks

**Comment by ntcuong** [comment]
Hi @khanguy00 !

All maintainers are still working every day, at:
[https://github.com/phananhnhat/bluezone-app](https://github.com/phucnguyen021295/bluezone-app)
[https://github.com/phananhnhat/bluezone-app](https://github.com/phananhnhat/bluezone-app)

Sorry for the late pull request.

Version 2.0 has just been merged into the main source repository. From version 2.0.0, All maintainers will pull requests regularly every day.

Hope you continue to contribute to the project next time :+1: .

**Comment by ntcuong** [comment]
> I haven't seen the maintainer actually reply any issue in this repo and its sister's repositories for a while.
> 
> The source code is also outdated with the app on Play Store [here](https://play.google.com/store/apps/details?id=com.mic.bluezone).
> 
> Looks like this repo is just a shadow, and the real one is a closed source project.
> 
> @ any maintainers: If you're still alive, and this project are continuing, please response and let the your Github community know. Thanks

**Comment by khanguy00** [comment]
It's good to hear. Thanks

**Comment by NgoHuy** [comment]
@ntcuong so long without update, I see that the development is active on your repository but no pull request.

**Comment by ferez96** [comment]
+1
