### ISSUE TITLE
Hỗ trợ thêm gps

### ISSUE THREAD

**Issue by minhnguyenvan95** [BluezoneGlobal/bluezone-app#21]
Gps cũng khá phổ biến trên điện thoại thông minh hiện nay . Mình nghĩ nên hỗ trợ thêm gps, các wifi location chứ không nhất thiết phải phụ thuộc vào bluetooth

**Comment by loclv** [comment]
Ví dụ check xem đã từng tới Đà Nẵng - nơi có nguy cơ lây nhiễm cao chưa cũng ok nhỉ?

**Comment by anhtuank7c** [comment]
Mình hoàn toàn **phản đối** ý kiến của bạn.
Hãy tôn trọng quyền riêng tư của người dùng và đọc tài liệu của google giùm.

https://www.google.com/covid19/exposurenotifications
