### ISSUE TITLE
Have the leaked keys been revoked? (commit 62db602b98dfb2bc17aef808a02767a796b17533)

### ISSUE THREAD

**Issue by huynhtrankhanh** [BluezoneGlobal/bluezone-app#34]

**Comment by khanguy00** [comment]
Tôi nghĩ bạn đang muốn nói đến file này:

https://github.com/BluezoneGlobal/bluezone-app/blob/c458fd07f58b2b50b04646d6e39270ea749e9299/android/google-services.json
